package:
  name: fiberfusing
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  git_url: https://github.com/MartinPdeS/FiberFusing.git

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

channels:
  - conda-forge
  - martinpdes

requirements:
  host:
    - python >=3.8
    - setuptools >=40.8.0
    - wheel
    - setuptools-scm >=8.0
    - pip
    - martinpdes::mpsplots
    - martinpdes::pyoptik
  run:
    - pyyaml ~= 6.0
    - martinpdes::mpsplots
    - martinpdes::pyoptik
    - scipy ~=1.14
    - pydantic ~=2.9
    - numpy ~=1.26
    - tabulate ~=0.9


about:
  home: https://github.com/MartinPdeS/PyFinitDiff
  license: MIT
  summary: "A package fiber fusing configuration simulating the transverse fusion of fiber optics."
  description: FiberFusing is a library that simulate the fusing of fiber optics through scanning flame. It's compuation is based on "The shape of the taper" from Birks.
  dev_url: https://github.com/MartinPdeS/PyFinitDiff
  doc_url: https://pyfinitdiff.readthedocs.io
  license_file: LICENSE
  keywords:
    - fiber optics
    - fusion
    - fiber components

test:
  imports:
    - FiberFusing
  requires:
    - pytest >=0.6
    - pytest-cov >=2.0
    - pytest-json-report ~=1.5
    - mypy >=0.910
    - flake8 >=3.9
    - tox >=3.24
    - coverage ~=7.6
  commands:
    - python -m pytest
  source_files:
    - tests

extra:
  recipe-maintainers:
    - MartinPdeS