# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os, sys
from pathlib import Path
from sphinx_gallery.sorting import ExplicitOrder




DocPath = Path( os.getcwd() ).parent


html_logo = os.path.join(DocPath,"images/Logo.png")
CSS_path = os.path.join(DocPath,"_static/default.css")

def setup(app):
    app.add_css_file(CSS_path)


autodoc_mock_imports = ['numpy',
                        'matplotlib',
                        'numpydoc']


PATH = os.path.join(os.path.dirname(__file__), '../..' )

sys.path.insert(0, PATH)


project   = 'FiberFusing'
copyright = '2021, Martin Poinsinet de Sivry-Houle'
author    = 'Martin Poinsinet de Sivry-Houle'


__location__ = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__)))
with open(os.path.join(__location__, '../../VERSION'), "r+") as f:
    version = release = f.read()


extensions = [
    'sphinx.ext.mathjax',
    'numpydoc',
    'sphinx_gallery.gen_gallery'
]



ExampleDirectory = ["../../Examples/"]

sphinx_gallery_conf = {
     'examples_dirs': ExampleDirectory,   # path to example scripts
     'gallery_dirs': "./ExamplesGallery/",   # path to where to save gallery generated output
     'image_scrapers': ('matplotlib'),
     'ignore_pattern': '/__',
     'thumbnail_size': [300,300],
     'download_all_examples': False,
     'line_numbers': True,
     'remove_config_comments': True,
     'default_thumb_file': os.path.abspath(html_logo),
     'subsection_order': ExplicitOrder(ExampleDirectory),
     'notebook_images': html_logo,
}


autodoc_default_options = {
    'members':          True,
    'undoc-members':    False,
}

numpydoc_show_class_members = False
autodoc_member_order = 'bysource'
autodoc_typehints = "description"
# Add any paths that contain templates here, relative to this directory.

#bibtex_bibfiles = ['refs.bib']
#bibtex_encoding = 'latin'
#bibtex_default_style = 'unsrt'

templates_path = ['_templates']


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

import os

#html_extra_path = ['../../tests/Examples/']
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = None

pygments_style = 'sphinx'
# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#


html_theme = 'sphinxdoc'

#html_theme_path = [ovs_sphinx_theme.get_theme_dir()]


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".

html_static_path = ['_static']

html_css_files = ['default.css']


# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'FiberFusingdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'FiberFusing.tex', 'FiberFusing Documentation',
     'Martin Poinsinet de Sivry-Houle', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'supymodes', 'FiberFusing Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'FiberFusing', 'FiberFusing Documentation',
     author, 'FiberFusing', 'One line description of project.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------
