name: Ubuntu-Workflow


permissions:
  contents: write

on:
  workflow_call:
    inputs:
      python_version:
        type: string
        required: false
        default: "['3.10']"


jobs:
  job_create_wheel:
    name: "Python ${{ matrix.python-version[1] }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJson(inputs.python_version) }}
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: "Set-up: Python ${{ matrix.python-version[1] }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version[0] }}

      - name: "Install: Dependencies"
        run: |
          python -m pip install --upgrade pip
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 xdotool
          Xvfb :99 &
          export DISPLAY=:99

      - name: "Run: Tests"
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]
          pytest -s
          python setup.py bdist_wheel


      - name: "Upload: Wheel"
        if: ${{ inputs.publish_wheel == true }}"
        uses: actions/upload-artifact@v3
        with:
          name: "manylinux_wheel_python${{ matrix.python-version[1] }}"
          path: ./dist/*










# -
