# .github/workflows/deploy_documentation.yml
name: Documentation

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  documentation:
    name: Run the documentation building tools
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: "Set-up: Python 3.10"
        uses: actions/setup-python@v4
        id: cp310
        with:
            python-version: "3.10"

      - name: "Install: Dependencies for headless server"
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install libgl1-mesa-glx xvfb

      - name: "Checkout requirements and files for testing"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install everything, run the tests, produce the .coverage file
        run: |
          python -m pip install wheel build
          python -m build --wheel
          python -m pip install .[documentation]

      - name: "Build: documentation"
        shell: bash
        run: |
            make -C docs html

      - name: "Upload: GitHub Pages"
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: crazy-max/ghaction-github-pages@v3
        with:
            target_branch: gh-pages
            build_dir: docs/build/html
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}