name: Deploy

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

permissions:
    contents: write

jobs:
    build_pure_python:
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/build_pure_python_package@master
            with:
                python-version: '3.10'

    publish_coverage:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_coverage@master
            with:
                package-name: FiberFusing
                python-version: "3.10"
                auth: ${{ secrets.GIST_TOKEN }}
                gistID: 49dc3e2c41180ac9018ae803a8acd177

    publish_documentation:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_documentation@master
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                package-name: FiberFusing
                python-version: "3.10" #no documentation for python 3.7 (pickle5 not presentË˜)

    publish_wheel:
        if: "contains(github.event.head_commit.message, '[publish]')"
        needs: [build_pure_python, publish_documentation, publish_coverage]
        runs-on: ubuntu-latest
        steps:
          - uses: MartinPdeS/MPSActions/publish_pypi@master
            with:
                python-version: "3.10"
                password: ${{ secrets.PYPI_API_TOKEN }}
